# Generated by Django 4.2.3 on 2023-08-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FaceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("top", models.IntegerField()),
                ("right", models.IntegerField()),
                ("bottom", models.IntegerField()),
                ("left", models.IntegerField()),
                ("emotion", models.CharField(max_length=50)),
                ("age", models.CharField(max_length=20)),
                ("gender", models.CharField(max_length=10)),
            ],
        ),
    ]
